// angular/Container.ts
import { Component, Input } from "@angular/core";

import { container, ContainerSize } from "../compositions/container";
import { TClassname, compose } from "classy-ui";

@Component({
  selector: "container",
  template: '<div [class]="container"><ng-content></ng-content></div>'
})
export class Container {
  @Input() size: ContainerSize;
  @Input() tokens: TClassname;
  container: string;
  ngOnInit() {
    this.container = compose(container(this.size), this.tokens);
  }
}

// src/react/Container.tsx
import { TClassname, compose } from "classy-ui";
import * as React from "react";

import { ContainerSize, container } from "../compositions/container";

type Props = {
  size?: ContainerSize;
  tokens?: TClassname;
};

export const Container: React.FC<Props> = ({ children, size, tokens }) => (
  <div className={compose(container(size), tokens)}>{children}</div>
);
