// vue/Container.vue
<template>
  <div :class="container">
    <slot></slot>
  </div>
</template>
<script>
import { container } from "../compositions/container";
import { compose } from "classy-ui";

export default {
  name: "container",
  props: ["size", "tokens"],
  data: component => ({
    container: compose(container(component.size), component.tokens)
  })
};
</script>

// src/react/Container.tsx
import { TClassname, compose } from "classy-ui";
import * as React from "react";

import { ContainerSize, container } from "../compositions/container";

type Props = {
  size?: ContainerSize;
  tokens?: TClassname;
};

export const Container: React.FC<Props> = ({ children, size, tokens }) => (
  <div className={compose(container(size), tokens)}>{children}</div>
);
