// angular/PrimaryButton.ts
import { Component, Input } from "@angular/core";

import { primaryButton } from "../compositions/buttons";

@Component({
  selector: "primary-button",
  template:
    '<button [disabled]="disabled" [class]="primaryButton(disabled)">{{text}}</button>'
})
export class PrimaryButton {
  @Input() text: string;
  @Input() disabled: boolean = false;
  primaryButton = primaryButton;
}

// vue/PrimaryButton.vue
<template>
  <button :disabled="disabled" :class="primaryButton(disabled)">
    <slot></slot>
  </button>
</template>
<script>
import { primaryButton } from "../compositions/buttons";

export default {
  name: "primaryButton",
  props: ["disabled"],
  data: () => ({
    primaryButton
  })
};
</script>
